### ISSUE TITLE
Add helper to locate SLA files

### ISSUE THREAD

**Issue by tetsuo-cpp** [lifting-bits/sleigh#12]
As per @pgoodman's comment at https://github.com/lifting-bits/sleigh/pull/9#issuecomment-948047563, we should look into a way of exposing a helper that finds SLA files in the SLEIGH installation that it belongs to. Ideally it should just look like this:
```c++
/*
* Returns a string containing the path to the .sla file for a given architecture.
* @param arch: The architecture for which we want to find a .sla file
* @return: An absolute path to the .sla file
* @throw std::invalid_argument: An unknown arch is provided.
*/
std::string FindSlaFile(const std::string& arch);
```

**Comment by ekilmer** [comment]
I'm curious how you are planning to do this? Ideally this function would work when the linked library (or executable being run) is in the build directory _and_ after it is installed somewhere. The build directory path can be a hard-coded (hard-calculated) absolute path using CMake, but the install path should be relative to the executable or library so as to have a relocatable package. I think LLVM has some machinery to do this in clang to find libcxx headers 🤔

**Comment by pgoodman** [comment]
The way in Remill is to embed the `CMAKE_INSTALL_PREFIX`-related location, the build folder location, and then some random search paths. We could use `configure_file` to create a bunch of paths in a header file, then search down a list. There should also be the ability to pass in a list of paths to prefer as hints.
