### ISSUE TITLE
Compiling on Windows

### ISSUE THREAD

**Issue by 20urc3** [lifting-bits/sleigh#190]
Hi team! Thanks for your work, it's really nice! Hope the Ghidra team accept your request and maintain themself a standalone sleigh version.

However, for the moment i'm trying to build it using your repo but without success on windows. When i run the command ```cmake --install build --prefix ./install``` it result in:
```CMake Error at build/cmake_install.cmake:39 (file):
file INSTALL cannot find
"C:/Users/s0urc3/sleigh/build/Release/sla.lib": File exists"
 ```

Any idea wassup?

**Comment by ekilmer** [comment]
Hello! Thank you!

What were your CMake configuration and build commands?

You might need to specify the build type with your install command (`--config <CMAKE_BUILD_TYPE>`). In CI we use the `ci-windows` CMake preset, which uses the Visual Studio (multi-config) build generator and requires specifying the build type.

Untested, but something like the following should work
```
cmake --preset ci-windows
cmake --build build --config RelWithDebInfo
cmake --install build --config RelWithDebInfo --prefix ./install
```

**Comment by 20urc3** [comment]
Anyway to specify the visual studio version?

```
-- Found Git: C:/Program Files/Git/cmd/git.exe (found version "2.41.0.windows.1")
-- Using Ghidra version 10.3 at git ref Ghidra_10.3_build
-- Populating ghidrasource
CMake Error at CMakeLists.txt:16 (project):
  Generator

    Visual Studio 17 2022

  could not find any instance of Visual Studio.



-- Configuring incomplete, errors occurred!
CMake Error at C:/Program Files/CMake/share/cmake-3.27/Modules/FetchContent.cmake:1650 (message):
  CMake step for ghidrasource failed: 1
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.27/Modules/FetchContent.cmake:1802:EVAL:2 (__FetchContent_directPopulate)
  C:/Program Files/CMake/share/cmake-3.27/Modules/FetchContent.cmake:1802 (cmake_language)
  C:/Program Files/CMake/share/cmake-3.27/Modules/FetchContent.cmake:2016 (FetchContent_Populate)
  src/setup-ghidra-source.cmake:83 (FetchContent_MakeAvailable)
  CMakeLists.txt:16 (include)

-- Configuring incomplete, errors occurred!
```

**Comment by ekilmer** [comment]
Yes, change the line in the `CMakePresets.json` file here https://github.com/lifting-bits/sleigh/blob/f1d1eab45f7e8d3499be56253b8256aab9eb5213/CMakePresets.json#L80

More documentation on the Visual Studio generators (and others) https://cmake.org/cmake/help/latest/manual/cmake-generators.7.html#visual-studio-generators

**Comment by 20urc3** [comment]
Hi. Thanks for your help on this! 
I followed those step:
- git clone https://github.com/lifting-bits/sleigh.git
- cd sleigh
- cmake --preset ci-windows
- cmake -B build -S .
- cmake --build build --config RelWithDebInfo

But when i execute: `cmake --install build --config RelWithDebInfo --prefix ./install` it errors in as follow:

```
CMake Error at build/cmake_install.cmake:64 (file):
  file INSTALL cannot find
  "C:/Users/s0urc3/sleigh/build/docs/html": No error.
```

**Comment by ekilmer** [comment]
Hmmmm. It looks like an issue with building the documentation. Did you see an error when building or during config about Doxygen?

In any case, it's probably easiest to just disable it.

```sh
cmake --preset ci-windows -Dsleigh_BUILD_DOCUMENTATION=OFF
cmake --build build --config RelWithDebInfo
cmake --install build --config RelWithDebInfo --prefix ./install
```

**Comment by 20urc3** [comment]
I confirm that this work:

```
cmake --preset ci-windows -Dsleigh_BUILD_DOCUMENTATION=OFF
cmake --build build --config RelWithDebInfo
cmake --install build --config RelWithDebInfo --prefix ./install
```

Thanks mate! I'm gonna play with the tool a bit, hope to contribute to the doc here :)
