### ISSUE TITLE
Example `sleigh-lift` invocation no longer works

### ISSUE THREAD

**Issue by tetsuo-cpp** [lifting-bits/sleigh#36]
There seems to be a regression at https://github.com/lifting-bits/sleigh/commit/387f9b09b7eb8ea5d0fada9ddf501e9a85c291ee which has broken disassembly. I'll eyeball the SLEIGH changes that went into that release and see if I submit a patch to Ghidra.

Before:
```
tetsuo@Alexs-MacBook-Pro install % ./bin/sleigh-lift disassemble x86-64.sla 4881ecc00f0000
0x00000000: SUB RSP,0xfc0
```
After:
```
tetsuo@Alexs-MacBook-Pro install % ./bin/sleigh-lift disassemble x86-64.sla 4881ecc00f0000
0x00000000: DEC AX
0x00000001: DEC AX
0x00000002: DEC AX
0x00000003: DEC AX
0x00000004: DEC AX
0x00000005: DEC AX
0x00000006: DEC AX
```

**Comment by tetsuo-cpp** [comment]
@pgoodman This is the issue you saw earlier.

**Comment by tetsuo-cpp** [comment]
Looks like the culprit is [this commit](https://github.com/NationalSecurityAgency/ghidra/commit/41d0be6b95a1fd92fb07ed46b925f4be4f78a924). Just playing around to figure out which part of the patch is responsible for this regression.

**Comment by ekilmer** [comment]
Not sure if this is related, but I found out you have to specify a `.pspec` file for 64 bit x86 disassembling, but maybe setting `longMode` is more correct.

Code reference from [Mishegos PR](https://github.com/trailofbits/mishegos/pull/1115):
https://github.com/ekilmer/mishegos/blob/712981d442f30207a4adf9acc052774024bc5be3/src/worker/ghidra/ghidra.cc#L91-L95

**Comment by tetsuo-cpp** [comment]
Interesting, thanks for the tip @ekilmer. I'll try both methods tomorrow and let you know how it goes.

**Comment by pgoodman** [comment]
@tetsuo-cpp the stuff @ekilmer linked to related to pspec files fixed my 16-bit issue :-)
