### ISSUE TITLE
Add a `--version` argument

### ISSUE THREAD

**Issue by artemdinaburg** [lifting-bits/sleigh#42]
The binaries (sleigh-lift) should take a `--version` argument that outputs relevant version information; ideally we want:

* Git commit hash of the build
* Any ghidra component versions used

**Comment by ekilmer** [comment]
Just a note that the `git` executable should not be _required_ to build sleigh. If someone downloads a zip of the repo without git info, they should still be able to build and get _some_ version info like Ghidra commit/version used (because that is known by CMake).
