### ISSUE TITLE
Build sleigh with C++11

### ISSUE THREAD

**Issue by ekilmer** [lifting-bits/sleigh#77]
The upstream sleigh source code builds with C++11 standard:

https://github.com/NationalSecurityAgency/ghidra/blob/b6181be1e44cd2de24f1493cb45148fc873e8487/Ghidra/Features/Decompiler/src/decompile/cpp/Makefile#L47

We should also build the libraries with that standard.

The other tools can be built with higher standards, but we should try to stick as close as possible to upstream's build settings and options.

**Comment by tetsuo-cpp** [comment]
Can we still build the support libraries with C++17? We make use of `std::filesystem` which is really helpful so it'd be good if we could avoid rewriting that.

**Comment by ekilmer** [comment]
> Can we still build the support libraries with C++17?

I think so. Using CMake's [`target_compile_features`](https://cmake.org/cmake/help/v3.15/manual/cmake-compile-features.7.html#requiring-language-standards), we can set `cxx_std_11` for all of Ghidra's sleigh library targets and `cxx_std_17` for the support library/tool targets that use `std::filesystem` and CMake should take care of adding the correct `-std=c++xx` compiler flag.
